export const TEACHER_DATA: Record<string, string> = {
  "Dra. Sri Mularsih": "196706201994122001", "Drs. Fiva Widiarto": "196510231996011002", "Wahyu Budi Susapti, S.Pd, MM.": "197207291997022002",
  "Marwoto, S.Pd, S.Kom": "196904082000121001", "Sri Endah Swarastuti, S.Pd": "197407022003122004", "Dra. Cukat Budi Rahayu": "196901121994032010",
  "Dra. Diah Ayu Supriyanti": "196603261994122004", "Justina Trirahaju Leksanawati, S.Pd., M.Si.": "197104162003122006", "Sri Wahyuni, S.Pd": "197008022002122004",
  "Dwi Agus Tri M.M., S.Pd": "197102232002122004", "Sumardi, S.Pd., S.Kom": "197305272003121002", "Agung Pamuji, S.Pd": "197402132005011008",
  "Retnowati, S.Pd": "197303272005012009", "Tony Eka Martin Wibowo, S.Si.": "197912092005011004", "Nur Romlah, S.Pd": "197509082008012008",
  "Deddy Suwito, S.Kom": "197209022006041013", "Agus Wuryanto, S.Pd": "197503222006041002", "Tri Puji Utami, S.Kom": "198304252009032009",
  "Puji Pertiwi Sayekti, S.Pd": "196805102005012011", "Nur Fajriyahti, S.Pd.": "197005212007012014", "Srirahayu, S.Pd.": "197408042008012009",
  "Romidin, S.Pd": "197505052008011021", "Teguh Cahyono, S.Pd.": "198110232006041010", "Seto Eko Purwanto, S.Si": "197804232010011009",
  "Nelly Amaliyah, S.Psi": "197907032010012019", "Satyo Nugroho, S.Kom.": "197807142009031006", "Suratno, S.Pd": "198409032010011012",
  "Vektor Realita Aditopo, S.Pd": "198603312011011003", "Adi Setiawan, S.Pd.": "199012292014021001", "Galih Tyas Anjari, S.Pd.": "199201212014022001",
  "Deti Lestiyorini, S.Pd.": "198912142014022001", "Mahzun, S.Pd I": "197601072008011009", "Sugeng Pitoyo, S.Pd.": "197311032008011002",
  "Asriyatun, S.Pd": "199208262020122009", "Nur Laeli, S.Pd": "199704112020122011", "Sepudin Zupri, S.Kom": "197010222022211001",
  "Arif Nurokhman, S.Pd": "198010172022211002", "Elis Sugiarti, S.Pd.": "198503072022212028", "Sudiyarti, S.Pd": "198511182022212012",
  "Otiah, S.Pd.": "198802242022212013", "Novaristya Widyasmara Pamungkas, S.Pd": "198811042022211004", "Menik Yuni Hartini, S.Pd.": "198906292022212008",
  "Baiq Nur Aisyah, S.Pd.": "198909222022212005", "Sulistiono, S.Pd.": "199112202022211007", "Isria Rizqona Firdausyi, S.Pd.": "199201312022212011",
  "Hindun Fatmawati, S.Pd.": "199210042022212007", "Ana Nurlatifah, S.Pd.": "199304032022212014", "Dwi Inayah Rahmawati, M.Pd.": "199311282022212011",
  "Danu Dwi Jatmiko, S.Pd.": "199401192022211003", "Restu Afri Widhi Hastutiningsih, S.Pd.": "199604032022212009", "Nining Setiani, S.Pd.": "199610102022212008",
  "Kukuh Pribadi, S.Pd.": "198610232022211006", "Yekti Apriyoni, S.Pd.": "197804272023212002", "Novita Adhimurti, S.Pd.": "197811142023212001",
  "Khamsyatun Yudiana, S.Pd.I.": "198207132023212011", "Nanang Cahyana, S.Pd.Ing.": "198603172023211003", "Waskito Ismu Hastomo, S.Pd.": "198606092023211007",
  "Lely Erawati, S.Pd.": "198708212023212018", "Septian Endro Laksono, S.Pd.": "199009052023211004", "Firmanika Rozaqi, S.Pd.": "199104242023212024",
  "Devi Artati, S.Pd.": "199210112023212020", "Soviatun Khasanah, S.Pd.": "199606302023212006", "Miftah Iskandar, S.Pd.": "198512112023211006",
  "Dista Puspitasari Adi, S.Pd.": "198603182024212004", "Rita Wijiarti, S.Pd.": "199410172024212021", "Safa Aulia Astri, S.Sos": "199607212024212021",
  "Agus Sutono, S.Pd.": "197406182025211007", "Yanti Karadina, S.Pd.": "197512172025212006", "Widia Sukaesih, S.E.": "197810082025212008",
  "Triyanto, S.Pd.": "198411252025211021", "Inayatul Munawaroh, S.Pd.": "199301062025212023", "Danu Setio Aji, S.Pd.": "199310162025211021",
  "Hera Dwi Suryandari, S.Pd.": "199312262025212012", "Slamet Suparman, S.Pd.": "-", "Devi Dwi Wahyuni, S.Pd.": "-", "Muhammad Idris Afandi, S.S., M.Pd.": "-"
};

export const PROMPT_TEMPLATES: Record<string, string> = {
    'identifikasi_murid': `Saya ingin menuliskan identifikasi murid Berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, saya mengidentifikasi kesiapan peserta didik dari aspek pengetahuan awal, minat belajar, dan kebutuhan individual. Identifikasi ini akan membantu saya menyusun strategi dan pendekatan pembelajaran yang tepat agar setiap siswa dapat mencapai kompetensi yang diharapkan. Sajikan dalam bentuk daftar poin. Hindari penggunaan format Markdown (seperti tanda bintang untuk tebal atau daftar).`,
    'identifikasi_materi': `Saya ingin menuliskan identifikasi materi pelajaran berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, materi pelajaran mencakup pengetahuan faktual, konseptual, prosedural, dan metakognitif. Materi dirancang relevan dengan kehidupan nyata peserta didik dan aplikatif dalam berbagai konteks, serta memperkuat nilai karakter yang mendukung pembelajaran bermakna dan menyenangkan. Sajikan dalam bentuk daftar poin. Hindari penggunaan format Markdown.`,
    'lintas_disiplin': `Saya ingin menuliskan lintas disiplin ilmu berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, pembelajaran dapat diintegrasikan lintas disiplin, khususnya dengan mata pelajaran yang mendukung penguatan pemahaman siswa secara holistik. Hal ini akan memperluas wawasan dan memberi makna kontekstual dalam pembelajaran. Sajikan dalam bentuk daftar poin. Hindari penggunaan format Markdown.`,
    'tujuan_pembelajaran': `Anda adalah guru {MATA_PELAJARAN} kelas {KELAS} fase {FASE} yang akan merancang modul ajar pembelajaran mendalam berdasarkan capaian pembelajaran "{CAPAIAN_PEMBELAJARAN}", saya ingin menyusun tujuan pembelajaran yang merinci kompetensi yang harus dikuasai murid dalam beberapa pertemuan. Tujuan pembelajaran akan dirumuskan secara spesifik dan terukur dengan memuat subjek belajar (Audience), kata kerja operasional (Behavior), konteks (Condition), dan tingkat pencapaian (Degree). Kata kerja operasional mengandung level kognitif taksonomi bloom yaitu menerapkan dan menganalisis. Tujuan ini akan menjadi dasar dalam merancang aktivitas belajar, pengalaman bermakna, dan asesmen yang relevan. Buatkan Tujuan untuk pembelajaran beberapa pertemuan dan dituliskan setiap pertemuan. Sajikan dalam bentuk daftar poin. Hindari penggunaan format Markdown.`,
    'topik_pembelajaran': `Tuliskan rekomendasi topik pembelajaran berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, topik pembelajaran ditentukan agar sesuai dengan kebutuhan peserta didik dan mampu mendorong pembelajaran yang mendalam serta kontekstual. Topik ini juga mendukung pengembangan kompetensi yang utuh secara pengetahuan, keterampilan, dan sikap. Buatkan topiknya untuk beberapa pertemuan. Sajikan dalam bentuk daftar poin. Hindari penggunaan format Markdown.`,
    'praktik_pedagogis': `Berikan rekomendasi Model/Strategi/Metode berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, yang mendukung aktivitas belajar aktif, kolaboratif, dan bermakna. Uraikan berdasarkan kesesuaian dengan Tujuan Pembelajaran tersebut untuk beberapa pertemuan. Model pembelajaran akan digunakan untuk mendorong keterlibatan peserta didik secara optimal untuk mencapai dimensi profil lulusan penalaran kritis, kolaborasi, dan komunikasi. Sajikan dalam bentuk daftar poin, bukan uraian teks. Berikan rekomendasi untuk setiap pertemuan meliputi model, metode, strategi. Hindari penggunaan format Markdown.`,
    'kemitraan_pembelajaran': `Tuliskan rekomendasi siapa saja mitra pembelajaran yang dapat berkolaborasi dan berperan berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, pembelajaran akan melibatkan kolaborasi dengan berbagai pihak seperti guru lain, orang tua, atau komunitas. Kemitraan ini bertujuan memperluas makna pembelajaran dan menumbuhkan keterlibatan peserta didik secara sosial. Sajikan dalam bentuk daftar poin, bukan uraian teks. Hindari penggunaan format Markdown.`,
    'lingkungan_pembelajaran': `Tuliskan identifikasi lingkungan belajar berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, lingkungan pembelajaran dirancang agar mendukung interaksi aktif antara peserta didik melalui kombinasi ruang fisik, virtual, dan budaya belajar yang positif. Lingkungan ini akan mendorong siswa menjadi pembelajar yang reflektif dan mandiri. Sajikan dalam bentuk daftar poin, bukan uraian teks. Hindari penggunaan format Markdown.`,
    'pemanfaatan_digital': `Berikan rekomendasi 3 jenis pemanfaatan digital berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, saya akan memanfaatkan teknologi digital untuk memperkuat interaksi, kolaborasi, serta asesmen dalam pembelajaran. Teknologi yang digunakan akan disesuaikan agar mendukung prinsip pembelajaran yang bermakna dan menggembirakan. Sajikan dalam bentuk daftar poin, bukan uraian teks. Hindari penggunaan format Markdown.`,
    'pengalaman_awal': `Buatkan secara ringkas dan jelas langkah kegiatan awal dengan durasi 15 menit berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, Susunlah kegiatan awal yang menerapkan prinsip pembelajaran berkesadaran, bermakna, dan menggembirakan. Kegiatan ini mencakup apersepsi, motivasi, dan pengkondisian yang membangun semangat serta keterhubungan dengan pengalaman siswa. Awali dengan mengucap salam kemudian kegiatan berdoa dan mengecek kehadiran. Identifikasi prinsip pembelajaran yang digunakan. Sajikan dalam format teks biasa tanpa Markdown.`,
    'pengalaman_inti': `Buatkan Langkah-langkah kegiatan inti dengan durasi 260 menit (atau menyesuaikan kebutuhan) berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}. Prinsip pembelajaran yang digunakan tetap mindful (berkesadaran), meaningful (bermakna), dan joyful (menggembirakan) agar peserta didik aktif menggali makna dari materi. Identifikasi prinsip pembelajaran yang digunakan. Buatkan aktivitas pembelajaran pada pembelajaran mendalam dengan tahapan sebagai berikut: Memahami, Mengaplikasikan, Merefleksi. Aktivitas pembelajaran yang memuat memahami, mengaplikasikan, merefleksi memiliki kaitan dengan sintaks dan metode pembelajaran dari: {PRAKTIK_PEDAGOGIS}. Kegiatan pembelajaran inti untuk menggali Dimensi Profil Lulusan (DPL) yaitu kemampuan penalaran kritis, kolaborasi, dan komunikasi. DPL dituliskan diakhir kalimat pada aktivitas dengan diberi tanda kurung. Topik pembelajaran adalah {TOPIK}. Sajikan dalam format teks biasa tanpa Markdown.`,
    'pengalaman_penutup': `Buatkan secara ringkas dan jelas langkah kegiatan penutup dengan durasi 5 menit berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, penutup pembelajaran dilakukan dengan menyimpulkan materi, memberikan umpan balik, merencanakan kegiatan selanjutnya dan doa kemudian diakhiri salam. Identifikasi prinsip pembelajaran yang digunakan. Sajikan dalam format teks biasa tanpa Markdown.`,
    'asesmen_awal': `Buatkan asesmen awal berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN} untuk mengetahui kesiapan dan pengetahuan awal peserta didik. Buatkan 2 atau 3 soal beserta jawabannya (pilih antara esai, uraian, atau pilihan ganda) sesuai level kognitif menerapkan dan menganalisis. Sajikan dalam format teks biasa tanpa Markdown.`,
    'asesmen_proses': `Buatkan asesmen pada proses pembelajaran berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}. Fokus pada observasi dan diskusi. Buatkan satu contoh rubrik penilaian sederhana dalam bentuk tabel yang menilai 2 atau 3 aspek (misal: kolaborasi, komunikasi). Sertakan rangkuman singkat tentang jenis, bentuk, dan teknik asesmen formatif yang relevan di awal. Sajikan dalam format teks biasa tanpa Markdown.`,
    'asesmen_akhir': `Buatkan asesmen pada akhir pembelajaran berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}. Buatkan 5 soal Pilihan Ganda (PG) tingkat HOTS (Higher-Order Thinking Skills) beserta kunci jawabannya. Sertakan juga kisi-kisi singkat untuk kelima soal tersebut. Sajikan dalam format teks biasa tanpa Markdown.`,
    'lampiran_diagnostik': `Buatkan instrumen tes diagnostik non-kognitif peserta didik dalam format dokumen Word yang rapi, sistematis, dan siap cetak. Instrumen ini ditujukan untuk peserta didik jenjang {KELAS} – Fase {FASE} dan mencakup 10 aspek utama sebagai berikut: 1. Identitas Peserta Didik (Nama Lengkap, Nama Panggilan, Kelas, No Absen, Tanggal Pengisisan), 2. Petunjuk Pengisian, 3. Minat Belajar (4 pernyataan, skala Likert 1–5), 4. Motivasi Belajar (4 pernyataan, skala Likert 1–5), 5. Sikap terhadap Pembelajaran (4 pernyataan, skala Likert 1–5), 6. Gaya Belajar (1 pertanyaan pilihan ganda: Visual, Auditori, Kinestetik, dengan deskripsi singkat untuk tiap pilihan), 7. Kecerdasan Emosional (4 pernyataan, skala Likert 1–5), 8. Penyesuaian Sosial (4 pernyataan, skala Likert 1–5), 9. Relasi Sosial dalam Lingkup Keluarga (4 pernyataan, skala Likert 1–5), 10. Kebiasaan Belajar di Rumah (4 pernyataan, skala Likert 1–5), 11. Refleksi Diri (3 pertanyaan isian singkat terbuka). Formatkan bagian skala Likert dalam bentuk tabel agar mudah dibaca dan diisi, dengan kolom: Sangat Tidak Setuju – Tidak Setuju – Netral – Setuju – Sangat Setuju. Gunakan bahasa yang sesuai dengan jenjang dan usia peserta didik, serta susun dengan heading dan subjudul yang jelas untuk tiap bagian. Tambahkan: Judul di bagian atas dokumen : INSTRUMEN TES DIAGNOSTIK NON-KOGNITIF PESERTA DIDIK, Catatan penutup untuk guru, tentang bagaimana hasil instrumen ini dapat digunakan untuk merancang pembelajaran berdiferensiasi, serta mendukung komunikasi antara sekolah dan keluarga. Formatkan hasil akhir dalam bentuk teks yang siap disalin dan tanpa Markdown.`,
    'lampiran_rubrik_diskusi': `Berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, saya ingin membuat rubrik penilaian untuk aktivitas diskusi yang menilai kemampuan peserta didik dalam berkolaborasi, menyampaikan pendapat, memunculkan ide, serta bekerja sama secara aktif dalam kelompok. Rubrik disusun dalam bentuk tabel yang memuat aspek penilaian, indikator, skala penilaian (1–5), serta deskripsi kinerja peserta didik pada setiap tingkat pencapaian. Penilaian ini digunakan untuk mengukur keterampilan komunikasi, kerja sama tim, dan partisipasi aktif peserta didik dalam proses pembelajaran. Sajikan dalam format teks biasa tanpa Markdown.`,
    'lampiran_rubrik_presentasi': `Berdasarkan tujuan pembelajaran {TUJUAN_PEMBELAJARAN}, saya ingin menyusun rubrik penilaian untuk aktivitas presentasi yang menilai kemampuan peserta didik dalam berbicara di depan umum, keberanian mengajukan pertanyaan terhadap hasil kerja kelompok lain, serta kontribusi dalam memaksimalkan kerja kelompok. Rubrik disusun dalam format tabel yang mencakup aspek penilaian, indikator ketercapaian, skala penilaian (1–5), dan deskripsi performa pada setiap tingkat. Penilaian ini bertujuan mengukur keterampilan komunikasi, keberanian, serta akuntabilitas peserta didik dalam kegiatan presentasi. Sajikan dalam format teks biasa tanpa Markdown.`,
    'lampiran_lkpd': `Anda adalah seorang Guru {MATA_PELAJARAN} kelas {KELAS} fase {FASE}. Buatkan Lembar Kerja Peserta Didik (LKPD) yang lengkap dan terstruktur berdasarkan sintaks pembelajaran {PRAKTIK_PEDAGOGIS}, dengan topik {TOPIK}. Tujuan pembelajaran yang menjadi acuan adalah {TUJUAN_PEMBELAJARAN}. LKPD ini bertujuan untuk mengembangkan dimensi profil lulusan yang relevan. LKPD harus mencakup bagian-bagian berikut secara lengkap: Identitas diri di LKPD: nama peserta didik, mata pelajaran, no absen, kelas, tanggal. Petunjuk penggunaan LKPD: berisi instruksi langkah-langkah mengerjakan, alat yang dibutuhkan, dan cara menjawab. Sintaks Pembelajaran, tuliskan tahapan kegiatan belajar sesuai sintaks, lalu berikan aktivitas siswa dan kolom untuk siswa mengerjakan. Pengalaman Belajar Mendalam, mencakup: Memahami: sajikan materi, gambar, atau teks ringkas yang harus diamati/dibaca, lalu berikan pertanyaan pemahaman (minimal 3 soal). Mengaplikasikan: buat tugas kasus nyata yang sesuai konteks kehidupan siswa, berikan instruksi kerja yang jelas, dan ruang jawaban siswa. Merefleksikan: berikan pertanyaan refleksi (2–3 soal) yang menuntun siswa untuk meninjau proses belajarnya, kesulitan yang dihadapi, serta rencana perbaikan atau tindak lanjut. Bagian Penutup: ucapan penyemangat, catatan guru (opsional), serta kolom cek pemahaman diri siswa (checklist atau skala sederhana). Gunakan bahasa yang komunikatif, sesuai jenjang, dan dorong pembelajaran aktif, bermakna, berkesadaran, dan menggembirakan. LKPD harus muncul secara utuh dengan isi yang lengkap, bukan hanya berupa kerangka atau daftar isi. Sajikan dalam format teks biasa tanpa Markdown.`,
    'lampiran_materi': `Anda adalah seorang Guru {MATA_PELAJARAN} kelas {KELAS} fase {FASE}. Buatkan materi ajar lengkap dengan topik {TOPIK} dan mengacu pada tujuan pembelajaran {TUJUAN_PEMBELAJARAN}. Materi ajar harus mendukung pengembangan dimensi profil lulusan yang relevan. Materi ajar harus ditulis secara utuh, mencakup: Judul dan Tujuan Pembelajaran di bagian awal. Pendahuluan atau Apersepsi: paragraf pembuka yang menghubungkan materi dengan kehidupan nyata siswa atau pengetahuan sebelumnya. Isi Materi: jelaskan secara sistematis konsep utama, fakta, prosedur, atau prinsip yang perlu dipahami siswa. Sertakan contoh konkret, ilustrasi, atau analogi. Tugas Ringan atau Pemantik Diskusi: berikan 2–3 pertanyaan atau tugas singkat untuk menguji pemahaman awal. Penutup dan Refleksi Singkat: rangkuman poin penting dan ajakan untuk berpikir kritis atau melanjutkan eksplorasi. Gunakan gaya bahasa yang komunikatif, sesuai dengan jenjang usia peserta didik, serta dukung pembelajaran aktif, kontekstual, dan menyenangkan. Materi ajar harus bisa digunakan langsung oleh guru untuk kegiatan belajar di kelas maupun pembelajaran mandiri. Sajikan dalam format teks biasa tanpa Markdown.`
};

export const SECTIONS_TO_GENERATE: { promptKey: string; target: any; title: string }[] = [
    { promptKey: 'identifikasi_murid', target: 'identifikasiPeserta', title: 'Identifikasi Murid' },
    { promptKey: 'identifikasi_materi', target: 'identifikasiMateri', title: 'Identifikasi Materi' },
    { promptKey: 'lintas_disiplin', target: 'desainLintasDisiplin', title: 'Lintas Disiplin' },
    { promptKey: 'topik_pembelajaran', target: 'desainTopik', title: 'Topik Pembelajaran' },
    { promptKey: 'praktik_pedagogis', target: 'desainPedagogis', title: 'Praktik Pedagogis' },
    { promptKey: 'kemitraan_pembelajaran', target: 'desainKemitraan', title: 'Kemitraan' },
    { promptKey: 'lingkungan_pembelajaran', target: 'desainLingkungan', title: 'Lingkungan Belajar' },
    { promptKey: 'pemanfaatan_digital', target: 'desainDigital', title: 'Pemanfaatan Digital' },
    { promptKey: 'pengalaman_awal', target: 'pengalamanAwal', title: 'Kegiatan Awal' },
    { promptKey: 'pengalaman_inti', target: 'pengalamanInti', title: 'Kegiatan Inti' },
    { promptKey: 'pengalaman_penutup', target: 'pengalamanPenutup', title: 'Kegiatan Penutup' },
    { promptKey: 'asesmen_awal', target: 'asesmenAwal', title: 'Asesmen Awal' },
    { promptKey: 'asesmen_proses', target: 'asesmenProses', title: 'Asesmen Proses' },
    { promptKey: 'asesmen_akhir', target: 'asesmenAkhir', title: 'Asesmen Akhir' },
    { promptKey: 'lampiran_diagnostik', target: 'lampiranDiagnostik', title: 'Lampiran Diagnostik' },
    { promptKey: 'lampiran_rubrik_diskusi', target: 'lampiranRubrikDiskusi', title: 'Lampiran Rubrik Diskusi' },
    { promptKey: 'lampiran_rubrik_presentasi', target: 'lampiranRubrikPresentasi', title: 'Lampiran Rubrik Presentasi' },
    { promptKey: 'lampiran_lkpd', target: 'lampiranLkpd', title: 'Lampiran LKPD' },
    { promptKey: 'lampiran_materi', target: 'lampiranMateri', title: 'Lampiran Materi Ajar' },
];

export const INITIAL_RPM_DATA = {
  satuanPendidikan: 'SMK Negeri 1 Purbalingga',
  namaGuru: '',
  nipGuru: '',
  kelas: '',
  semester: '',
  fase: '',
  mataPelajaran: '',
  elemen: '',
  materiAjar: '',
  alokasiWaktu: '',
  identifikasiPeserta: '',
  identifikasiMateri: '',
  dimensiProfil: {},
  desainCapaian: '',
  desainLintasDisiplin: '',
  desainTujuan: '',
  desainTopik: '',
  desainPedagogis: '',
  desainKemitraan: '',
  desainLingkungan: '',
  desainDigital: '',
  pengalamanAwal: '',
  pengalamanInti: '',
  pengalamanPenutup: '',
  asesmenAwal: '',
  asesmenProses: '',
  asesmenAkhir: '',
  lampiranDiagnostik: '',
  lampiranRubrikDiskusi: '',
  lampiranRubrikPresentasi: '',
  lampiranLkpd: '',
  lampiranMateri: '',
  guruSignatureSrc: null
};
